"use client"

import Link from "next/link"
import {
  TriangleAlert,
  ArrowRight,
  Upload,
  Sparkles,
  Building2,
  Users,
  Phone,
  ShieldCheck,
  Brain,
  FileBarChart,
  Search as SearchIcon,
  Database,
  CheckCircle2,
  Circle,
} from "lucide-react"

/* ------------------------------------------------------------------ */
/*  Pipeline stages -- ordered exactly as a workstream would flow      */
/* ------------------------------------------------------------------ */

const pipeline: {
  stage: number
  title: string
  subtitle: string
  icon: React.ElementType
  capabilities: string[]
  href?: string
  accent?: string
}[] = [
  {
    stage: 1,
    title: "Ingest & Standardise",
    subtitle:
      "The single biggest time sink today: re-keying unstructured expert data from network emails into trackers. AI handles parsing, deduplication, and field standardisation across networks -- populating a central database that auto-fills every downstream step.",
    icon: Upload,
    href: "/upload",
    accent: "text-primary",
    capabilities: [
      "Bulk upload from any expert network (CSV, email paste, or direct integration)",
      "AI-driven parsing of unstructured profiles and screening responses",
      "Cross-network field standardisation and deduplication",
      "Central database populated once -- every subsequent step auto-fills from it",
      "Profiles can be updated manually or enriched through subsequent network uploads (existing records are matched and merged)",
      "Auto-removal of target-company mentions in PEG contexts",
    ],
  },
  {
    stage: 2,
    title: "Track & Shortlist",
    subtitle:
      "Replace the shared Excel tracker with a single live view. Teammates can tag experts into shortlist groups -- customer, competitor, target, AI survey recipient, and more -- with all profile data already filled in from ingestion.",
    icon: Users,
    href: "/experts",
    capabilities: [
      "Lifecycle tracking: Recommended \u2192 Shortlisted \u2192 Scheduled \u2192 Completed",
      "Group-based shortlisting (e.g. customer, competitor, target, AI survey)",
      "All expert details auto-populated -- no re-typing from emails or other tabs",
      "Supervisor-ready sharing without copy-paste across Excel, email, or slides",
    ],
  },
  {
    stage: 3,
    title: "Calls & Spend",
    subtitle:
      "A call tracker that manages itself. Enter the scheduled time and the rest is handled: budget roll-ups (scheduled vs. completed vs. cancelled), forecast spend, and auto-populated fields that consultants currently maintain by hand in spreadsheets.",
    icon: Phone,
    href: "/calls",
    capabilities: [
      "Auto-populated call details from the central expert database",
      "Dynamic spend tracking: scheduled, completed, cancelled, and forecast",
      "End-of-day summaries and upcoming-call email digests",
      "Avoided-cost reporting and status updates triggered by outcomes",
    ],
  },
  {
    stage: 4,
    title: "Enrich & Classify",
    subtitle:
      "Augment profiles with data you would otherwise look up manually. GenAI anonymises expert titles for safe sharing, and business intelligence integrations (e.g. Helix) pull in company industry, FTE headcount, and descriptions. The system also flags current vs. former employees and checks departure dates to confirm experts can be contacted.",
    icon: Building2,
    capabilities: [
      "Anonymised titles generated by GenAI for client-safe sharing",
      "Company industry, FTE headcount, and descriptions from BI tools (e.g. Helix)",
      "Current vs. former employee classification with departure-date checks",
      "Normalised roles, companies, and seniority levels across networks",
    ],
  },
  {
    stage: 5,
    title: "Compliance & Clearance",
    subtitle:
      "Cross-check every profile against internal databases and client advisor lists you upload to flag or block experts that calls should not be booked with. CID clearance lets you mark whole companies or individuals as cleared -- and in a full implementation, auto-populates the CID request forms (project lead, contact name and role, rationale) that are currently filled out by hand, repeatedly, through a separate tool.",
    icon: ShieldCheck,
    capabilities: [
      "Cross-check against client advisors, BEN advisors, and do-not-contact lists",
      "Flag or block profiles that should not be booked through networks",
      "CID clearance: mark whole companies or individual experts as cleared",
      "Auto-populate CID request forms (project lead, contact details, rationale) -- defined once, reused for every request",
      "In-app button-based approval with full audit trail -- no more losing clearance decisions in email threads, reducing the risk of calls booked by mistake",
    ],
  },
  {
    stage: 6,
    title: "Transcripts & KPI Extraction",
    subtitle:
      "Upload call transcripts so they are stored, accessible, and queryable in one place. AI handles the administrative processing -- not insight extraction, which requires human judgement -- acting as a first pass that must be verified before sharing.",
    icon: Brain,
    href: "/ai-surveys",
    capabilities: [
      "Auto-generated summaries so users can quickly identify which transcript(s) they need",
      "KPI extraction into the call tracker (e.g. NPS scores for customer calls) -- populated automatically where applicable",
      "Flag references in the text that may need anonymising before client sharing (first-pass only; requires manual review)",
      "Rename and standardise transcript files for consistent storage",
      "Separate workspace for AI interview billing and tracking",
    ],
  },
  {
    stage: 7,
    title: "Search & Discovery",
    subtitle:
      "Two types of search in one interface. Expert search combines classic database filters (company, departure date, customer vs. competitor, etc.) with natural language to build shortlists faster. Transcript search lets you filter to a subset of calls -- e.g. only a certain competitor, or only customer transcripts -- then ask for supporting quotes, rather than uploading everything into a separate ChatGPT session each time.",
    icon: SearchIcon,
    href: "/search",
    capabilities: [
      "Expert search: database filters + natural-language queries to surface the right profiles",
      "Transcript search: filter by expert type, company, or call group, then query for quotes to support slide arguments",
      "Eliminates re-uploading subsets of transcripts into ChatGPT for each new question",
      "Future: link quotes back to their source location in the transcript for easy cross-checking against hallucinations",
    ],
  },
  {
    stage: 8,
    title: "Reconciliation & Reporting",
    subtitle: "Clean close-out and network settlement",
    icon: FileBarChart,
    capabilities: [
      "Structured summary tables for network reconciliation",
      "Cost verification with clear audit trail",
      "Expert-usage reporting to reduce end-of-project back-and-forth",
      "Team end-of-day email summaries -- formatted and ready to send",
      "All tables exportable in pre-formatted layouts ready to copy-paste into emails or slides",
      "Project data can be cleared automatically at close-out in line with company data retention policies and project timelines",
    ],
  },
]

/* ------------------------------------------------------------------ */
/*  Required data inputs                                               */
/* ------------------------------------------------------------------ */

const dataInputBuckets: {
  label: string
  tag: string
  tagColor: string
  accentColor: string
  description: string
  items: string[]
}[] = [
  {
    label: "Readily available",
    tag: "Ready now",
    tagColor: "bg-emerald-100 text-emerald-800",
    accentColor: "bg-emerald-500",
    description: "Data the team already has to hand for every workstream.",
    items: [
      "Unstructured expert profile data from networks (email paste or CSV export)",
      "Call transcripts (human and AI interviews)",
      "Client advisor lists uploaded per project for compliance cross-checks",
    ],
  },
  {
    label: "Internal setup required",
    tag: "Internal",
    tagColor: "bg-amber-100 text-amber-800",
    accentColor: "bg-amber-500",
    description:
      "Sourced from within Bain; needs integration or one-time upload.",
    items: [
      "BEN advisor details and advisors flagged for fraud by Compliance",
      "CID connection for auto-filing clearance forms and marking companies / experts as safe to contact",
    ],
  },
  {
    label: "Third-party integrations",
    tag: "Future",
    tagColor: "bg-sky-100 text-sky-800",
    accentColor: "bg-sky-500",
    description:
      "External services that unlock full automation; the trickiest to implement.",
    items: [
      "Direct expert network API feeds to auto-populate the tracker (removing the manual data ingestion step entirely)",
      "Business intelligence platforms (e.g. D&B Hoovers, Gain.pro) for company industry, FTE counts, and descriptions",
    ],
  },
]

/* ------------------------------------------------------------------ */
/*  Prototype status                                                   */
/* ------------------------------------------------------------------ */

const status: { done: boolean; text: string }[] = [
  { done: true, text: "App shell, navigation, and Bain design system" },
  { done: true, text: "TypeScript data model and localStorage CRUD layer" },
  { done: false, text: "CSV upload with deduplication" },
  { done: false, text: "Data tables with sort, filter, column hiding, and pagination" },
  { done: false, text: "Settings: export / import JSON, reset data" },
  { done: false, text: "AI-powered profile parsing and enrichment" },
  { done: false, text: "Compliance cross-checks and CID clearance workflow" },
  { done: false, text: "Vector-embedded search and RAG queries" },
  { done: false, text: "LLM transcript extraction and summarisation" },
  { done: false, text: "End-of-project reconciliation tables" },
]

export default function OverviewPage() {
  return (
    <div className="mx-auto max-w-5xl px-6 py-10">
      {/* Submission broken banner */}
      <div className="mb-8 rounded-lg border-2 border-red-300 bg-red-50 px-5 py-4">
        <div className="flex items-start gap-3">
          <div className="flex h-8 w-8 shrink-0 items-center justify-center rounded-full bg-red-100">
            <TriangleAlert className="h-4 w-4 text-red-600" />
          </div>
          <div>
            <p className="text-sm font-semibold text-red-900">
              Note: the data upload feature is currently broken
            </p>
            <p className="mt-1 text-sm leading-relaxed text-red-700">
              I{"'"}ve rolled back to a previous stable version and am
              re-implementing features as quickly as possible. See the
              prototype progress tracker at the bottom of this page for
              current status.
            </p>
          </div>
        </div>
      </div>

      {/* Hackathon banner */}
      <div className="mb-8 flex items-start gap-3 rounded-lg border border-amber-200 bg-amber-50 px-4 py-3">
        <TriangleAlert className="mt-0.5 h-4 w-4 shrink-0 text-amber-600" />
        <div>
          <p className="text-sm font-medium text-amber-900">
            Hackathon prototype
          </p>
          <p className="mt-0.5 text-xs leading-relaxed text-amber-700">
            Browser-only demo with synthetic seed data. All data is stored
            locally in your browser -- changes do not persist between sessions
            and cannot be shared between users.
          </p>
        </div>
      </div>

      {/* ============================================================ */}
      {/*  SECTION 1 -- Hero + Value Propositions                        */}
      {/* ============================================================ */}
      <section className="mb-16">
        <h1 className="text-2xl font-semibold tracking-tight text-foreground text-balance">
          Helmsman
        </h1>
        <p className="mt-2 max-w-3xl text-sm leading-relaxed text-muted-foreground">
          The end-to-end operating system for expert network workstreams --
          replacing fragmented spreadsheets, email chains, and manual processes
          with a single, intelligent platform.
        </p>

        <div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
          {/* 1 -- Reduced Admin */}
          <div className="group relative overflow-hidden rounded-lg border border-border bg-card p-5 transition-colors hover:border-primary/20 hover:bg-primary/[0.02]">
            <div className="flex h-10 w-10 items-center justify-center rounded-lg bg-primary/8 ring-1 ring-primary/15">
              <Sparkles className="h-5 w-5 text-primary" />
            </div>
            <h3 className="mt-4 text-sm font-semibold text-foreground">
              Reduced Typing & Admin
            </h3>
            <ul className="mt-2 flex flex-col gap-1.5">
              <li className="flex items-start gap-2 text-xs leading-relaxed text-muted-foreground">
                <span className="mt-1.5 block h-1 w-1 shrink-0 rounded-full bg-primary/40" />
                Eliminate manual data entry, copy-paste, and tracker maintenance
              </li>
              <li className="flex items-start gap-2 text-xs leading-relaxed text-muted-foreground">
                <span className="mt-1.5 block h-1 w-1 shrink-0 rounded-full bg-primary/40" />
                AI-driven parsing and auto-populated fields
              </li>
              <li className="flex items-start gap-2 text-xs leading-relaxed text-muted-foreground">
                <span className="mt-1.5 block h-1 w-1 shrink-0 rounded-full bg-primary/40" />
                Focus on expert selection, not spreadsheet wrangling
              </li>
            </ul>
          </div>

          {/* 2 -- Increased Coverage */}
          <div className="group relative overflow-hidden rounded-lg border border-border bg-card p-5 transition-colors hover:border-primary/20 hover:bg-primary/[0.02]">
            <div className="flex h-10 w-10 items-center justify-center rounded-lg bg-primary/8 ring-1 ring-primary/15">
              <Users className="h-5 w-5 text-primary" />
            </div>
            <h3 className="mt-4 text-sm font-semibold text-foreground">
              Increased Expert Coverage
            </h3>
            <ul className="mt-2 flex flex-col gap-1.5">
              <li className="flex items-start gap-2 text-xs leading-relaxed text-muted-foreground">
                <span className="mt-1.5 block h-1 w-1 shrink-0 rounded-full bg-primary/40" />
                Review and shortlist more experts in the same time window
              </li>
              <li className="flex items-start gap-2 text-xs leading-relaxed text-muted-foreground">
                <span className="mt-1.5 block h-1 w-1 shrink-0 rounded-full bg-primary/40" />
                Standardised profiles and smart filtering
              </li>
              <li className="flex items-start gap-2 text-xs leading-relaxed text-muted-foreground">
                <span className="mt-1.5 block h-1 w-1 shrink-0 rounded-full bg-primary/40" />
                Broader coverage without compromising quality
              </li>
            </ul>
          </div>

          {/* 3 -- Automated Outputs */}
          <div className="group relative overflow-hidden rounded-lg border border-border bg-card p-5 transition-colors hover:border-primary/20 hover:bg-primary/[0.02]">
            <div className="flex h-10 w-10 items-center justify-center rounded-lg bg-primary/8 ring-1 ring-primary/15">
              <FileBarChart className="h-5 w-5 text-primary" />
            </div>
            <h3 className="mt-4 text-sm font-semibold text-foreground">
              Automated Reporting
            </h3>
            <ul className="mt-2 flex flex-col gap-1.5">
              <li className="flex items-start gap-2 text-xs leading-relaxed text-muted-foreground">
                <span className="mt-1.5 block h-1 w-1 shrink-0 rounded-full bg-primary/40" />
                Budgeting and spend tracking via a live dashboard
              </li>
              <li className="flex items-start gap-2 text-xs leading-relaxed text-muted-foreground">
                <span className="mt-1.5 block h-1 w-1 shrink-0 rounded-full bg-primary/40" />
                Export ready-to-send email digests and team updates
              </li>
              <li className="flex items-start gap-2 text-xs leading-relaxed text-muted-foreground">
                <span className="mt-1.5 block h-1 w-1 shrink-0 rounded-full bg-primary/40" />
                KPI extraction and auto-anonymised transcripts
              </li>
            </ul>
          </div>

          {/* 4 -- Unified Interface */}
          <div className="group relative overflow-hidden rounded-lg border border-border bg-card p-5 transition-colors hover:border-primary/20 hover:bg-primary/[0.02]">
            <div className="flex h-10 w-10 items-center justify-center rounded-lg bg-primary/8 ring-1 ring-primary/15">
              <Database className="h-5 w-5 text-primary" />
            </div>
            <h3 className="mt-4 text-sm font-semibold text-foreground">
              Unified Interface
            </h3>
            <ul className="mt-2 flex flex-col gap-1.5">
              <li className="flex items-start gap-2 text-xs leading-relaxed text-muted-foreground">
                <span className="mt-1.5 block h-1 w-1 shrink-0 rounded-full bg-primary/40" />
                One platform connecting Bain{"'"}s existing tools
              </li>
              <li className="flex items-start gap-2 text-xs leading-relaxed text-muted-foreground">
                <span className="mt-1.5 block h-1 w-1 shrink-0 rounded-full bg-primary/40" />
                CID clearance, network portals, and compliance lists
              </li>
              <li className="flex items-start gap-2 text-xs leading-relaxed text-muted-foreground">
                <span className="mt-1.5 block h-1 w-1 shrink-0 rounded-full bg-primary/40" />
                Firmographic data -- industry, FTE counts, company descriptions
              </li>
            </ul>
          </div>
        </div>
      </section>

      {/* ============================================================ */}
      {/*  DIVIDER                                                       */}
      {/* ============================================================ */}
      <div className="mb-16 border-t border-border" />

      {/* ============================================================ */}
      {/*  SECTION 2 -- Pipeline ("How it works")                       */}
      {/* ============================================================ */}
      <section className="mb-16">
        <div className="mb-10 flex items-end gap-4">
          <div>
            <p className="text-[11px] font-semibold uppercase tracking-widest text-primary">
              Pipeline
            </p>
            <h2 className="mt-1 text-xl font-semibold tracking-tight text-foreground">
              How it works
            </h2>
            <p className="mt-1.5 max-w-2xl text-sm leading-relaxed text-muted-foreground">
              Eight stages replacing spreadsheets, emails, and manual lookups
              with a single automated flow.
            </p>
          </div>
        </div>

        <div className="grid gap-4 sm:grid-cols-2">
          {pipeline.map((step) => {
            const Icon = step.icon
            return (
              <div
                key={step.stage}
                className="group flex flex-col rounded-lg border border-border bg-card transition-colors hover:border-primary/20"
              >
                {/* Card header */}
                <div className="flex items-center gap-3 border-b border-border px-5 py-3.5">
                  <span className="flex h-7 w-7 shrink-0 items-center justify-center rounded-full bg-primary text-primary-foreground text-[11px] font-bold">
                    {step.stage}
                  </span>
                  <Icon className="h-4 w-4 shrink-0 text-primary/60" />
                  <h3 className="text-sm font-semibold text-foreground">
                    {step.title}
                  </h3>
                  {step.href && (
                    <Link
                      href={step.href}
                      className="ml-auto inline-flex items-center gap-1 rounded-full bg-primary/8 px-2.5 py-0.5 text-[10px] font-medium text-primary ring-1 ring-primary/15 transition-colors hover:bg-primary/15"
                    >
                      Demo
                      <ArrowRight className="h-2.5 w-2.5" />
                    </Link>
                  )}
                </div>

                {/* Card body */}
                <div className="flex flex-1 flex-col px-5 py-4">
                  <p className="text-xs leading-relaxed text-muted-foreground">
                    {step.subtitle}
                  </p>
                  <ul className="mt-3 flex flex-1 flex-col gap-1.5">
                    {step.capabilities.map((cap, j) => (
                      <li
                        key={j}
                        className="flex items-start gap-2 text-xs leading-relaxed text-foreground/80"
                      >
                        <span className="mt-1.5 block h-1 w-1 shrink-0 rounded-full bg-primary/40" />
                        {cap}
                      </li>
                    ))}
                  </ul>
                </div>
              </div>
            )
          })}
        </div>
      </section>

      {/* ============================================================ */}
      {/*  DIVIDER                                                       */}
      {/* ============================================================ */}
      <div className="mb-16 border-t border-border" />

      {/* ============================================================ */}
      {/*  SECTION 3 -- Data Requirements + Prototype Progress           */}
      {/* ============================================================ */}
      <section className="mb-16">
        <p className="text-[11px] font-semibold uppercase tracking-widest text-primary">
          Requirements
        </p>
        <h2 className="mt-1 text-xl font-semibold tracking-tight text-foreground">
          Required Input Data
        </h2>
        <p className="mt-1.5 max-w-2xl text-sm leading-relaxed text-muted-foreground">
          For full end-state functionality, Helmsman requires the following data
          sources -- grouped by availability and implementation effort.
        </p>

        <div className="mt-8 grid gap-5 sm:grid-cols-3">
          {dataInputBuckets.map((bucket, i) => (
            <div
              key={i}
              className="relative flex flex-col overflow-hidden rounded-lg border border-border bg-card"
            >
              {/* Accent top bar */}
              <div className={`h-1 w-full ${bucket.accentColor}`} />

              <div className="px-5 pt-4 pb-3">
                <div className="flex items-center gap-2">
                  <h3 className="text-sm font-semibold text-foreground">
                    {bucket.label}
                  </h3>
                  <span
                    className={`inline-flex rounded-full px-2 py-0.5 text-[10px] font-semibold ${bucket.tagColor}`}
                  >
                    {bucket.tag}
                  </span>
                </div>
                <p className="mt-1 text-xs leading-relaxed text-muted-foreground">
                  {bucket.description}
                </p>
              </div>

              <div className="border-t border-border" />

              <ul className="flex flex-1 flex-col gap-2.5 px-5 py-4">
                {bucket.items.map((item, j) => (
                  <li
                    key={j}
                    className="flex items-start gap-2.5 text-sm leading-relaxed text-foreground/80"
                  >
                    <span
                      className={`mt-2 block h-1.5 w-1.5 shrink-0 rounded-full ${bucket.accentColor}`}
                    />
                    {item}
                  </li>
                ))}
              </ul>
            </div>
          ))}
        </div>
      </section>

      <div className="mb-16 border-t border-border" />

      {/* Prototype progress */}
      <section className="mb-4">
        <p className="text-[11px] font-semibold uppercase tracking-widest text-primary">
          Status
        </p>
        <h2 className="mt-1 text-xl font-semibold tracking-tight text-foreground mb-6">
          Prototype Progress
        </h2>
        <div className="rounded-lg border border-border bg-card divide-y divide-border">
          {status.map((item, i) => (
            <div key={i} className="flex items-center gap-3 px-4 py-2.5">
              {item.done ? (
                <CheckCircle2 className="h-3.5 w-3.5 shrink-0 text-emerald-600" />
              ) : (
                <Circle className="h-3.5 w-3.5 shrink-0 text-muted-foreground/30" />
              )}
              <span
                className={[
                  "text-sm",
                  item.done ? "text-foreground" : "text-muted-foreground",
                ].join(" ")}
              >
                {item.text}
              </span>
            </div>
          ))}
        </div>
      </section>
    </div>
  )
}
