"use client"

import { Search, Filter, Users, FileText, Send } from "lucide-react"
import { PlaceholderSection } from "@/components/placeholder-section"

export function SearchContent() {
  return (
    <div className="space-y-6">
      {/* Prototype label */}
      <div className="rounded-lg border border-border bg-card px-4 py-3">
        <p className="text-xs text-muted-foreground">
          <span className="font-medium text-foreground">Prototype Simulation:</span>{" "}
          Search results are generated by keyword matching against seed data. In
          production this would use embedding-based semantic search.
        </p>
      </div>

      <div className="grid gap-6 lg:grid-cols-[280px_1fr]">
        {/* Left panel: filters */}
        <div className="space-y-4">
          <PlaceholderSection
            icon={Filter}
            title="Structured Filters"
            description="Expert attributes, call attributes, and survey attribute filters."
          />
          <div className="rounded-lg border border-border bg-card p-4 text-center">
            <p className="text-xs text-muted-foreground">
              Retrieval set preview: <span className="font-medium text-foreground">--</span> transcripts selected
            </p>
          </div>
        </div>

        {/* Main panel */}
        <div className="space-y-4">
          {/* Query box */}
          <div className="rounded-lg border border-border bg-card p-4">
            <div className="flex items-center gap-2">
              <Search className="h-4 w-4 text-muted-foreground" />
              <span className="text-sm text-muted-foreground">
                Natural language query box — e.g., &quot;Which experts discussed pricing pressure in pharma?&quot;
              </span>
            </div>
          </div>

          {/* Results tabs */}
          <div className="flex gap-1 rounded-lg border border-border bg-card p-1">
            <button className="flex items-center gap-1.5 rounded-md bg-secondary px-3 py-1.5 text-sm font-medium text-foreground">
              <Users className="h-3.5 w-3.5" />
              Experts
            </button>
            <button className="flex items-center gap-1.5 rounded-md px-3 py-1.5 text-sm font-medium text-muted-foreground hover:bg-secondary/60 hover:text-foreground">
              <FileText className="h-3.5 w-3.5" />
              Quotes / Transcript Hits
            </button>
          </div>

          <PlaceholderSection
            icon={Search}
            title="Search Results"
            description="Matching experts and transcript quote snippets will be displayed here."
          />

          {/* LLM placeholder */}
          <div className="rounded-lg border border-dashed border-border bg-card p-4 text-center">
            <div className="flex items-center justify-center gap-2 text-muted-foreground">
              <Send className="h-4 w-4" />
              <span className="text-sm">
                &quot;Send selected set to LLM&quot; — shows payload preview (no actual API call)
              </span>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}
