"use client"

import { useState } from "react"
import { Search, Filter, Users, FileText, Send } from "lucide-react"
import { PlaceholderSection } from "@/components/placeholder-section"
import { EmptyState } from "@/components/empty-state"
import { cn } from "@/lib/utils"

const resultTabs = ["Experts", "Quotes / Transcript Hits"]

export function SearchContent() {
  const [activeTab, setActiveTab] = useState("Experts")

  return (
    <div className="mt-6 space-y-6">
      {/* Prototype label */}
      <div className="rounded-lg border border-border bg-card px-5 py-3">
        <p className="text-xs text-muted-foreground">
          <span className="font-medium text-foreground">Prototype:</span>{" "}
          Search results will be generated by keyword matching against stored data.
          In production, this would use embedding-based semantic search.
        </p>
      </div>

      <div className="grid gap-6 lg:grid-cols-[280px_1fr]">
        {/* Left panel: filters */}
        <div className="space-y-4">
          <PlaceholderSection
            icon={Filter}
            title="Structured Filters"
            description="Expert attributes, call attributes, survey attributes, date ranges."
          />
          <div className="rounded-lg border border-border bg-card px-4 py-3 text-center">
            <p className="text-xs text-muted-foreground">
              Retrieval set:{" "}
              <span className="font-medium text-foreground">--</span>{" "}
              transcripts selected
            </p>
          </div>
        </div>

        {/* Main panel */}
        <div className="space-y-4">
          {/* Query box */}
          <div className="flex items-center gap-3 rounded-lg border border-border bg-card px-4 py-3">
            <Search className="h-4 w-4 shrink-0 text-muted-foreground" />
            <input
              type="text"
              placeholder='Natural language query -- e.g., "Which experts discussed pricing pressure in pharma?"'
              className="flex-1 bg-transparent text-sm text-foreground outline-none placeholder:text-muted-foreground"
              disabled
            />
          </div>

          {/* Results tabs */}
          <div className="flex gap-0.5 border-b border-border">
            {resultTabs.map((tab) => (
              <button
                key={tab}
                onClick={() => setActiveTab(tab)}
                className={cn(
                  "flex items-center gap-1.5 border-b-2 px-4 py-2.5 text-[13px] font-medium transition-colors",
                  activeTab === tab
                    ? "border-foreground text-foreground"
                    : "border-transparent text-muted-foreground hover:text-foreground"
                )}
              >
                {tab === "Experts" ? (
                  <Users className="h-3.5 w-3.5" />
                ) : (
                  <FileText className="h-3.5 w-3.5" />
                )}
                {tab}
              </button>
            ))}
          </div>

          <EmptyState
            icon={Search}
            title="No search results"
            description="Enter a query above or apply filters to search across experts and transcripts."
          />

          {/* LLM action placeholder */}
          <div className="flex items-center justify-center gap-2 rounded-lg border border-dashed border-border bg-secondary/30 px-4 py-3">
            <Send className="h-3.5 w-3.5 text-muted-foreground" />
            <span className="text-xs text-muted-foreground">
              {"\"Send selected set to LLM\" -- shows payload preview (no actual API call)"}
            </span>
          </div>
        </div>
      </div>
    </div>
  )
}
